### ISSUE TITLE
gcc-4.0.4: infrequently 0.5% ABORT: run.sh: line 72: cd: libcpp: error 02

### ISSUE THREAD

**Issue by bittorf** [fosslinux/live-bootstrap#103]
seen with a6630ff and qemu-386 with kernel 3.18.140 and 3G RAM.

see:
http://intercity-vpn.de/bootstrap/bootstrap.log-multilog-2-1618438037.txt

```
[...]
00h59m06s | checking for sysmp... no
00h59m06s | checking for getsysinfo... no
00h59m06s | checking for table... no
00h59m06s | checking for sysctl... no
00h59m06s | checking for __fsetlocking... yes
00h59m06s | checking whether canonicalize_file_name must be declared... yes
00h59m06s | checking for stdlib.h... (cached) yes
00h59m06s | checking for unistd.h... (cached) yes
00h59m06s | checking for getpagesize... (cached) yes
00h59m06s | checking for working mmap... yes
00h59m06s | checking for working strncmp... yes
00h59m06s | configure: creating ./config.status
00h59m06s | config.status: creating Makefile
00h59m06s | config.status: creating testsuite/Makefile
00h59m06s | config.status: creating config.h
00h59m06s | config.status: executing default commands
00h59m06s | run.sh: line 72: cd: libcpp: error 02
00h59m06s | Subprocess error 256
00h59m06s | ABORTING HARD
```

**Comment by stikonas** [comment]
Hmm, maybe `mkdir` call failed before `cd`. We are just `cd`'ing into a directory that was just created.

So not sure why this failed, maybe it was just one off error that is not reproducible...

**Comment by bittorf** [comment]
i have seen this during last mass-run 3 times...strange!

**Comment by stikonas** [comment]
Hmm, so it's not one off. The code that fails is here:
https://github.com/fosslinux/live-bootstrap/blob/9f83e1213ea65cf6f2687c0c789b969cdf4cb93a/sysa/gcc-4.0.4/pass1.sh#L72

I'm not sure what we can do. Since we run with `set -e` that means `mkdir` returned with exit code 0. So I'm puzzled why cd fails.
Any ideas?

**Comment by bittorf** [comment]
i will overload with an mkdir() function which always makes a sync, lets see if this helps

**Comment by stikonas** [comment]
We haven't seen this recently, maybe fixed?
