### ISSUE TITLE
End-state goals docs

### ISSUE THREAD

**Issue by vasi** [fosslinux/live-bootstrap#124]
This project is great! I love that it can take me from almost-nothing to a fairly complete OS.

One bit that's unclear to me is what the goals are for the built environment. Obviously not every package in the world should be added--so it'd be great to document at what stage it would be considered complete. Some possibilities:

1. Build enough to self-host: A kernel, python with `requests`, qemu
2. Build the prerequisites for some system that allows installing more software from source: Gentoo Prefix, pkgsrc, etc
3. Build enough to bootstrap some other distro: Linux From Scratch, GUIX, Gentoo (via bootstrap-portage), Debian (with rebootstrap), NetBSD (with build.sh), etc

Would love to hear your thoughts.

**Comment by fosslinux** [comment]
I currently see this as a two-stage project.

1. Have a fully working, bootstrapped, up-to-date functional C toolchain + supporting software (such as coreutils, bash shell), so it can be reasonably used for the second stage.
2. Have a number of "plugins", that add on to the end of `live-bootstrap`'s toolchain that bootstrap various other distros, such as those you mentioned.

I'm not sure if I would want those plugins in the same repository but it is the general idea.
