### ISSUE TITLE
psyntax.pp in mes

### ISSUE THREAD

**Issue by stikonas** [fosslinux/live-bootstrap#164]
We need to deal with https://git.savannah.gnu.org/cgit/mes.git/tree/mes/module/mes/psyntax.pp even if it is not used.

(there is also psyntax.pp.header but it is trivial)

**Comment by oriansj** [comment]
*HEAVY SIGH* After the untar, just delete the files and put a comment in about the removal of generated files.

and probably keep an eye out on future releases...

**Comment by stikonas** [comment]
We don't have `rm` this early but we can do `catm empty_file` and then `cp empty_file generated_file`.

**Comment by fosslinux** [comment]
Well, hoping it is unused...

**Comment by stikonas** [comment]
> Well, hoping it is unused...

It is.

**Comment by oriansj** [comment]
I added rm to mescc-tools-extra; no excuse not to nuke it from orbit and if it breaks the build or everything keeps working fine; we will know the absolute truth. Delete all generated files!!!
