### ISSUE TITLE
coreutils-5.0: Use of generated `false.c`, `dircolors.h`, `wheel.h`, `wheel-size.h`

### ISSUE THREAD

**Issue by schierlm** [fosslinux/live-bootstrap#176]
When looking at coreutils-5.0, the build uses 4 pre-generated files that are not part of the source repository.

- `false.c`: Can probably be generated from `true.c` via sed or patch

- `dircolors.c`: Can probably be stubbed, or the functionality patched out.

- `wheel{,-size}.h`: Probably exclude `factor` from the binaries to generate?

I did not look at coreutils-6.10 yet, so maybe there are similar pre-generated files.

**Comment by fosslinux** [comment]
This is quite bad, thank you for alerting us to that.

**Comment by stikonas** [comment]
I've now removed `factor` in https://github.com/fosslinux/live-bootstrap/commit/45924ae12a30ea3e0ba8731d3fef4163ee1a6aa2

Only coreutils 5 was affected.6.10 and 8.32 are fine.

**Comment by stikonas** [comment]
`dircolors.h` is not used in coreutils 5. It is only used in coreutils 8.32, so hopefully we can just rebuild it then (unless it needs newer perl).

**Comment by stikonas** [comment]
Actually coreutils 8.32 is built from snapshot, so there is not dircolors.h.

Should we bother deleting `dircolors.h` from coreutils 5 if it's not used (it's only used by `dircolors.c` but we don't build `dircolors` binary)?

**Comment by fosslinux** [comment]
I think fine as in your just merged PR, doesn't really harm to remove it.
