### ISSUE TITLE
automake-1.15.1 failed to build

### ISSUE THREAD

**Issue by stikonas** [fosslinux/live-bootstrap#184]
Probably some race condition

```
automake-1.15.1: compiling source.
make[1]: Entering directory `/usr/src/automake-1.15.1/build/automake-1.15.1'
make[1]: Leaving directory `/usr/src/automake-1.15.1/build/automake-1.15.1'
Updating ./doc/version.texi
  MAKEINFO doc/automake.info
  MAKEINFO doc/automake-history.info
  GEN      bin/automake
  GEN      bin/aclocal
  GEN      t/ax/shell-no-trail-bslash
  GEN      t/ax/cc-no-c-o
  GEN      runtest
  GEN      doc/aclocal.1
  GEN      doc/automake.1
  GEN      lib/Automake/Config.pm
  GEN      doc/aclocal-1.15.1
  GEN      doc/automake-1.15.1
  GEN      doc/amhello-1.0.tar.gz
doc/amhello-1.0.tar.gz: recipe failed.
See file '/usr/src/automake-1.15.1/build/automake-1.15.1/doc/amhello/amhello-output.tmp' for details
make: *** [doc/amhello-1.0.tar.gz] Error 1
```

**Comment by stikonas** [comment]
That is possibly caused by something broken in autotools. I'll be reworking autotools symlinks, so this might be fixed then.

**Comment by stikonas** [comment]
Still happens from time to time.

**Comment by stikonas** [comment]
`amhello-output.tmp` end with

```
  && make  install \
  && make  installcheck \
  && make  uninstall \
  && make  distuninstallcheck_dir="$dc_install_base" \
        distuninstallcheck \
  && chmod -R a-w "$dc_install_base" \
  && ({ \
       (cd ../.. && umask 077 && mkdir "$dc_destdir") \
       && make  DESTDIR="$dc_destdir" install \
       && make  DESTDIR="$dc_destdir" uninstall \
       && make  DESTDIR="$dc_destdir" \
            distuninstallcheck_dir="$dc_destdir" distuninstallcheck; \
      } || { rm -rf "$dc_destdir"; exit 1; }) \
  && rm -rf "$dc_destdir" \
  && make  dist \
  && rm -rf amhello-1.0.tar.gz \
  && make  distcleancheck \
  && cd "$am__cwd" \
  || exit 1
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: executing depfiles commands
make[2]: Entering directory `/usr/src/automake-1.15.1/build/automake-1.15.1/doc/amhello/amhello-1.0/_build/sub'
CDPATH="${ZSH_VERSION+.}:" && cd ../.. && autoconf-2.69
autom4te-2.69: cannot create autom4te.cache: No such file or directory
make[2]: *** [../../configure] Error 1
make[2]: Leaving directory `/usr/src/automake-1.15.1/build/automake-1.15.1/doc/amhello/amhello-1.0/_build/sub'
make[1]: *** [distcheck] Error 1
make[1]: Leaving directory `/usr/src/automake-1.15.1/build/automake-1.15.1/doc/amhello'
```

**Comment by doraskayo** [comment]
This is still happening and a bit annoying. It makes it hard to rely on live-bootstrap in other projects.

We need to figure out the race condition and avoid it completely and consistently.

**Comment by stikonas** [comment]
> This is still happening and a bit annoying. It makes it hard to rely on live-bootstrap in other projects.
> 
> We need to figure out the race condition and avoid it completely and consistently.

Yes, I've seen it too, not too frequently but it happened from time to time. Unfortunately, I wasn't able to spot anything suspicious that could cause it.

**Comment by nanonyme** [comment]
Do we happen to have this fix? https://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=commit;h=ea9d7d9f1fc8a2ed91a8017683acf424ac7886ed

**Comment by stikonas** [comment]
Might be worth applying this patch. But it would be hard to tell whether it fixes this bug :(

**Comment by nanonyme** [comment]
That's true. But it sees to be happening almost all the time now.

**Comment by stikonas** [comment]
> That's true. But it sees to be happening almost all the time now. So we would probably notice a difference if it actually affected anything.

That's not my impression here. Maybe this race condition is easier to trigger on your system. In which case it might be helpful if you could run it a few times with that patch... I can try to prepare PR for this

**Comment by nanonyme** [comment]
Some level of resuming would to be honest also help quite a lot both for problems like this and testing fixes. Building live-bootstrap is quite time-intensive even with a fast SSD.

**Comment by stikonas** [comment]
> Some level of resuming would to be honest also help quite a lot both for problems like this and testing fixes. Building live-bootstrap is quite time-intensive even with a fast SSD.

We already have that. There is `--early-preseed` and `--repo` arguments. `--early-preseed` can replace early binaries (before `bash` and packages are bootstrapped) and `--repo` is for other packages.

Anyway, I'm now preparing a pull request.

**Comment by stikonas** [comment]
> Anyway, I'm now preparing a pull request.
That will take more time. Unfortunately the patch does not apply cleanly, so I'll need to investigate.

**Comment by nanonyme** [comment]
No worries. We managed to get a build through after various attempts and are now trying to massage post live-bootstrap process to work.

**Comment by stikonas** [comment]
I'm having some problems with the patch, I suspect it needs newer `perl` that what we have in `live-bootstrap` at that stage. I've tried switching to `autoconf-2.71` instead at that stage but in `make` stage I'm getting the same error as with patched `autoconf-2.69`. Perhaps we need to fix the patch not to break our `perl`.

**Comment by stikonas** [comment]
Looks like mkdir command is failing for some reason. Possibly with the patch the failure is deterministic rather than random.

If I replace `perl`'s `mkdir` with `system("mkdir", $cache)` it does build. So perhaps we can try to use that and see if it helps.

**Comment by stikonas** [comment]
Let's remove `doc` from `Makefile.am`, this seems to get rid of race condition.
