### ISSUE TITLE
Different checksum on packages from different source

### ISSUE THREAD

**Issue by aretsan** [fosslinux/live-bootstrap#202]
Hi,

I noticed some different checksum when downloading coreutils.

When I download from http://git.savannah.gnu.org/cgit/coreutils.git/snapshot/coreutils-8.32.tar.gz, it has this checksum
6f7cfc0ac6717afb6ba1f41b0da43a713ba0dd97dec1227e32effc12d79f08c1  coreutils-8.32.tar.gz

But when I download from https://ftp.gnu.org/gnu/coreutils/coreutils-8.32.tar.gz, it has
d5ab07435a74058ab69a2007e838be4f6a90b5635d812c2e26671e3972fca1b8  coreutils-8.32.tar.gz.1

Similar thing happened to guile-3.0.7.tar.gz.

I wondered if this is expected or not.

**Comment by stikonas** [comment]
Oh and usually in live-bootstrap we use release tarballs (though there is a discussion whether we should continue to do so https://github.com/fosslinux/live-bootstrap/issues/177).

But in this particular case coreutils tarball does not contain all files required to rebuild pre-generated files, so we just ended up using git snapshot.

**Comment by stikonas** [comment]
And `guile-3.0.7.tar.gz` is different story:

tar.gz file contains https://github.com/schierlm/guile-psyntax-bootstrapping and it is not Guile but we use it to bootstrap guile.
whereas guile-3.0.7.tar.xz is Guile itself.
