### ISSUE TITLE
Pregenerated files in libtool 2.4.7

### ISSUE THREAD

**Issue by stikonas** [fosslinux/live-bootstrap#203]
libtool 2.4.7 imports the following pregenerated files via gnulib

`libtool/lib/uniwidth/width0.h`
`libtool/lib/uniwidth/width2.h`

I think our options are:
1. Rebuild it (might not be easy if rebuilding tool `gen-uni-tables.c` depends on newer gcc).
2. Switch to an older gnulib (That might not be an option if it depends on some new gnulib modules).
3. Revert addition of libtool 2.4.7.

**Comment by schierlm** [comment]
Another option might be to patch out the `wc_width` function from gnulib and remove the pregenerated files altogether. At least I could not find any place in libtool that would call it. And nothing else needs those widths tables. CMIIW.

**Comment by stikonas** [comment]
Yes, that's probably the simplest option then. I haven't checked it's usage.

**Comment by fosslinux** [comment]
A bit of further investigation has determined that these pregenerated files don't leave the gnulib tree, so they don't affect libtool-2.4.7.
