### ISSUE TITLE
https://zlib.net/zlib-1.2.12.tar.xz returns 404

### ISSUE THREAD

**Issue by schierlm** [fosslinux/live-bootstrap#209]
When downloading zlib sources, it fails as https://zlib.net/zlib-1.2.12.tar.xz returns 404.
Older versions of zlib (https://zlib.net/fossils/) seem to be only available as tar.gz, not tar.xz.

But in my opinion worse: The downloading just stops at that point (I did not notice any error message) and it tries to bootstrap anyway with only 70 files in `sysa/distfiles` (from line count of `sources` files there should be 132).

**Comment by stikonas** [comment]
Let's switch to fossils UR (I can upgrade to 1.2.13 at the same time ). Though that wouldn't yet fix lack of error message.

**Comment by stikonas** [comment]
Fix for immediate problem https://github.com/fosslinux/live-bootstrap/pull/211 but not for download failure.

**Comment by schierlm** [comment]
Thanks for fixing. To be honest, I am no longer sure about the thing with the error message. Seems I ran it without `--external-sources`, so it only downloaded stuff needed for sysa, not sysc (which does not include zlib). and did not notice as the chroot was created without `unshare -net` and just downloaded the files inside instead.

**Comment by stikonas** [comment]
I'll test it then in a couple of days if I have time and if there is not error then we can close this.
