### ISSUE TITLE
Missing checksums for packages use by qemu build

### ISSUE THREAD

**Issue by rick-masters** [fosslinux/live-bootstrap#213]
When I build with qemu, it fails with:
```
kexec-tools-2.0.22: creating package.
kexec-tools-2.0.22: no checksum stored!
Subprocess error 1
```
If the above is fixed, it fails again:
```
linux-4.9.10: install to fakeroot.
linux-4.9.10: creating package.
linux-4.9.10: no checksum stored!
Subprocess error 1
```

The checksums for those two packages were removed recently from sysa/SHA256SUMS.pkgs in this commit:
https://github.com/fosslinux/live-bootstrap/commit/31bc944dd314c64aa94ad349ad65ab6a572dfdb3

**Comment by fosslinux** [comment]
This is completely a silly oversight by me. Thank you!
