### ISSUE TITLE
ca-certificates fails due to expired certificates

### ISSUE THREAD

**Issue by rick-masters** [fosslinux/live-bootstrap#220]
When a certificate expires in the ca-certificates package that certificate is excluded from the package which results in a different package checksum, which fails the build.

I have a PR forthcoming which uses a special keyword IGNORECHECKSUM in place of the checksum in SHA256SUMS.pkgs which fixes this in the least invasive way I can think of. This would need to be replaced every time checksums are regenerated. Perhaps someone has a better idea...

**Comment by doraskayo** [comment]
It would most likely be best to keep expired certificates in the CA bundle for our use case. I think it can be achieved by patching this out:
https://github.com/curl/curl/blob/2bc1d775f510196154283374284f98d3eae03544/scripts/mk-ca-bundle.pl#L585-L593

**Comment by stikonas** [comment]
Another certificate expired.
