### ISSUE TITLE
Support live-bootstrapping only up to sysc_image and resuming sysc separately

### ISSUE THREAD

**Issue by nanonyme** [fosslinux/live-bootstrap#230]
Currently when you use chroot/bwrap method for live-bootstrapping, you need to chroot at the end of sysa. Allowing separate top-level sandboxes for sysa and sysc allows more flexible integration to build systems. Additionally, having separate sandbox for sysc allows even with direct rootfs usage dropping chroot permission from bwrap as you can simply create a new bwrap sandbox.

**Comment by nanonyme** [comment]
Looks like also splitting build like this with bwrap would help in cases like https://edition.cnn.com/2023/01/21/europe/turkey-cancels-swedish-defense-minister-visit-intl/index.html as when we drop the chroot permission, you might be able to run setuid bwrap just fine.

**Comment by fosslinux** [comment]
I like the idea; for chroot/bwrap only, though. This is not appropriate for QEMU/bare metal where we use kexec.

**Comment by nanonyme** [comment]
Right, there are already guards with regards to chroot https://github.com/fosslinux/live-bootstrap/blob/master/sysa/run.sh#L251

**Comment by stikonas** [comment]
Ideally this should be provided as an option (even in chroot and bwrap modes), while we could still use the old chroot method.

**Comment by nanonyme** [comment]
To be honest, in bwrap mode we probably should just always use separate sandboxes. It will already add extra code to add the separate sandboxes and to *drop* chroot permission inside bwrap (it's better to ensure that works since it's not guaranteed to be available for everyone using live-bootstrap) we would closer to triple the current amount of code. For chroot I'm ambivalent whether it buys much to use separate chroots rather than nested since you are root already when you use chroot.

**Comment by nanonyme** [comment]
So in other words
1. Extra option in bootstrap.cfg
2. Using bwrap implies this option is true

**Comment by nanonyme** [comment]
@stikonas I think we *probably* do not want to high-level expose this in chroot method since you *already* have chroot permission so splitting doesn't really help. But with bwrap it allows dropping a cap which may help when no user namespaces are available.
