### ISSUE TITLE
Typo in util-linux

### ISSUE THREAD

**Issue by stikonas** [fosslinux/live-bootstrap#244]
https://github.com/fosslinux/live-bootstrap/blob/4b5b0377184680de08dff87e0e7f4fa909a3bbec/sysa/util-linux-2.19.1/util-linux-2.19.1.sh#L21

Build string refers to `fdsik`. It should be `fdisk` but given that it still seems to work, do we even need it?

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign this issue to me.
