### ISSUE TITLE
No space left on device building in qemu mode

### ISSUE THREAD

**Issue by pder** [fosslinux/live-bootstrap#254]
live-bootstrap commit c062f2347c3074f62fb23 fails in qemu mode during the build of the linux kernel due to running out of disk space.

  CC      arch/x86/boot/regs.o
  CC      arch/x86/boot/string.o
  CC      arch/x86/boot/tty.o
  CC      arch/x86/boot/video.o
  CC      arch/x86/boot/video-mode.o
  CC      arch/x86/boot/version.o
  CC      arch/x86/boot/video-vga.o
  CC      arch/x86/boot/video-vesa.o
  CC      arch/x86/boot/video-bios.o
  LD      arch/x86/boot/setup.elf
  OBJCOPY arch/x86/boot/setup.bin
  OBJCOPY arch/x86/boot/vmlinux.bin
objcopy:arch/x86/boot/vmlinux.bin[.rodata..compressed]: No space left on device
make[1]: *** [arch/x86/boot/vmlinux.bin] Error 1
make: *** [bzImage] Error 2
Subprocess error 2
ABORTING HARD
Subprocess error
ABORTING HARD
[ 3803.444085] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
[ 3803.445057] CPU: 0 PID: 1 Comm: init Not tainted 6.1.0-1-686 #1  Debian 6.1.4-1

**Comment by fosslinux** [comment]
The disk space is very close to full at the moment. Are you using `--external-sources`? If so, clear your distfiles directory and let it re-download everything to ensure you don't have any unnecessary tarballs.
