### ISSUE TITLE
Use more reliable source of curl than sourceforce

### ISSUE THREAD

**Issue by nanonyme** [fosslinux/live-bootstrap#268]
Looks like http://master.dl.sourceforge.net/project/curl.mirror/curl-7_83_0/curl-7.83.0.tar.xz was deleted and can no longer be downloaded.

**Comment by nanonyme** [comment]
Looks like https://curl.se/download/ has old versions as well.

**Comment by nanonyme** [comment]
One option is live-bootstrap creates a repo on sourceforge and mirrors the upstream file there so there will be no one cleaning it up.

**Comment by fosslinux** [comment]
Gah, that is a little bit problematic, since we were relying on a non-HSTS source to grab curl from inside live-bootstrap...

**Comment by nanonyme** [comment]
Well, as said, you can mirror it there yourself and get correct version from upstream site

**Comment by fosslinux** [comment]
I'm not very fond of permanently requiring a mirror of software (the sources used in live-bootstrap should not be locked to the existence of live-bootstrap). For now, I might just update curl, and we can revisit the underlying problem later.

**Comment by nanonyme** [comment]
Sure. But the current source is even worse than if live-bootstrap project added mirror there. It's now maintained by random person not affiliated with curl project.

**Comment by stikonas** [comment]
I've switched to https://curl.se/download/  for now.
