### ISSUE TITLE
Running live-bootstrap with bare metal option should not require a serial port console

### ISSUE THREAD

**Issue by pder** [fosslinux/live-bootstrap#303]
I tried testing live-bootstrap on VirtualBox by running:

`rootfs.py -b -p`
`vboxmanage convertfromraw tmp/sysa/sysa.img sysa.vdi`

I then created a VM with 4096MB of RAM and attached the sysa.vdi disk.
When Fiwix and Linux are booted nothing appears on the screen because their console is redirected to a serial port.  I propose that when using the bare metal config option don't redirect the Fiwix and Linux consoles to /dev/ttyS0 which may not even exist.

A proposed solution is here involving writing BARE_METAL=True/False to bootstrap.cfg and checking this environment variable in kexec-fiwix.c

https://github.com/fosslinux/live-bootstrap/compare/master...pder:live-bootstrap:bare-metal-no-serial-console

**Comment by fosslinux** [comment]
That is a logical default to me. Feel free to open a PR for that.
