### ISSUE TITLE
/dev disk nodes not populated on sysc

### ISSUE THREAD

**Issue by ajherchenroder** [fosslinux/live-bootstrap#312]
I am working on creating a Gentoo prefix from a completed bootstrap. To get the scripts into the system I hacked the qemu initiation to pass through a usb mass storage device. Along the way I realized that the /dev disk nodes aren't populated on sysc but they are populated on sysb. I hacked a quick copy of the sysb script into the after.sh on sysc. In my mind, the nodes should be created prior to shifting control to the user. The user should be able to just mount an existing node from sysc.

**Comment by stikonas** [comment]
Yes, I agree  that /dev disk nodes should be mounted in sysc. It was probably just overlooked because nobody needed them yet. Would you be willing to make a PR?

And thanks for working on creating Gentoo prefix. This is something I'm interested too.

**Comment by ajherchenroder** [comment]
I need to clean up my hack and add support for NVME and cd dev nodes. Then I’ll try to figure out how to do a PR.

**Comment by stikonas** [comment]
Note that there are now some initial notes on bootstrapping Gentoo: https://mid-kid.root.sx/git/mid-kid/bootstrap/src/branch/master/gentoo-2024/gentoo.txt

**Comment by ajherchenroder** [comment]
Thanks, that looks to be quite the treasure trove. I’ll dig into it when I get home this weekend.Sent from my iPadOn Feb 26, 2024, at 7:16 PM, Andrius Štikonas ***@***.***> wrote:﻿
Note that there are now some initial notes on bootstrapping Gentoo: https://mid-kid.root.sx/git/mid-kid/bootstrap/src/branch/master/gentoo-2024/gentoo.txt
