### ISSUE TITLE
When building with the qemu option bash reports errors

### ISSUE THREAD

**Issue by ajherchenroder** [fosslinux/live-bootstrap#319]
I was testing some changes I made when I noticed the following messages
"bash: cannot set terminal process group (-1): Not a tty" and "bash: no job control in this shell". I normally do most of my testing under a chroot and I have never seen those messages before. Can someone please confirm if they get the same messages or have I broken something. The command I used was:

./rootfs.py -p --update-checksums -q

**Comment by stikonas** [comment]
I probably saw it before. It's just a warning, so I wouldn't worry about it (unless you really want to fix it).
