### ISSUE TITLE
pkg-config-0.29.2.tar.gz is no longer available from OSOUSL.

### ISSUE THREAD

**Issue by setupminimal** [fosslinux/live-bootstrap#320]
Currently, we get pkg-config-0.29.2.tar.gz from http://gentoo.osuosl.org/distfiles/pkg-config-0.29.2.tar.gz, but this link now 404s. Using a search engine suggests it's not just been moved, it's not hosted on that site at all anymore.

http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz looks like the canonical source, but it's not available over HTTP. Ditto with other mirrors I was able to find.

So either we need to find a mirror where this package is available via HTTP, re-order things so that CURL has SSL support by the time we download pkg-config (I'm not sure if this is possible), or do something clever with a HTTP-to-HTTPS proxy or similar.

**Comment by setupminimal** [comment]
Oh, now that I look, I see that we copy the curl package from sysa to sysc. Probably the simplest fix is to do the same with pkg-config. I'll test that to see if it works and report back.

**Comment by setupminimal** [comment]
When I try that, I get this error when moving from sysa to sysb:

```
[    0.936399] RAMDISK: gzip image found at block 0
[    0.970668] RAMDISK: incomplete write (9862 != 16384)
[    0.970978] write error
[    0.971163] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
```

So that doesn't work, although I'm not sure why. Maybe I'm filling up a disk? Either way, I'm not sure where to go from here.

**Comment by stikonas** [comment]
Yes, there are various space limitations in sysa. It's very hard to add any more stuff now.

Perhaps we should switch to `pkgconf`.

**Comment by setupminimal** [comment]
I worked around it by using download-dependencies.sh, and then hosting the local distfiles on a HTTP server and checking that as well as the official URL. It's sort of a hack and I think it only works when you're using QEMU, so probably switching to pkgconf is cleaner, but if you want my hack it's in my fork: https://github.com/setupminimal/live-bootstrap

**Comment by fosslinux** [comment]
This is... strange. I don't know where the file has gone from the Gentoo distfiles mirror. Downloading all the directory listings and grepping for pkg-config only shows old versions. Not sure why it's disappeared...

**Comment by nanonyme** [comment]
There have also been quite a lot of bugs in pkgconf. Be mentally prepared for patching and backports.

**Comment by andrewchambers** [comment]
It seems like the original URL at http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz is working again.

**Comment by nanonyme** [comment]
@andrewchambers that's a HTTPS redirect. Try curl -I
`Location: https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz`

**Comment by nanonyme** [comment]
@fosslinux I'm assuming you mentally have already done so but I suppose this is 1.0 blocker?

**Comment by fosslinux** [comment]
Oh, yes, but I should hope that this is not too hard to fix. I'm hoping I'll be able to find a reasonable solution in the next few days.

**Comment by fosslinux** [comment]
For now I've updated the pkg-config tarball to be from macports, which will work (it is HTTP-only allowed).

Although, I will still try out pkgconf later. For now this is fixed though.
