### ISSUE TITLE
Python 2.5 build failures with parallel build on

### ISSUE THREAD

**Issue by nanonyme** [fosslinux/live-bootstrap#321]
Noticed at https://gitlab.com/freedesktop-sdk/freedesktop-sdk-binary-seed/-/jobs/5292964461 with max jobs 12. Unclear how well reproducible.

**Comment by nanonyme** [comment]
@doraskayo suggested might be related to https://bugs.python.org/issue10013

**Comment by nanonyme** [comment]
https://github.com/python/cpython/commit/9828b56347f6171a532dce28c9dc5ab9bd2c8139.patch might be the real fix. The patch is under PSF.

**Comment by nanonyme** [comment]
It looks like fix was backported so it does not impact our 3.1.5.

**Comment by nanonyme** [comment]
Based on brief glance same bug may be present in 2.3.5. 2.0.1 tag does not exist in CPython git repository so didn't check yet.

**Comment by nanonyme** [comment]
@fosslinux how does copyright tag work with these? It looks like we would end up mostly using upstream patches.

**Comment by nanonyme** [comment]
Okay. Given the patch should be fine with just NEWS change *removed*, maybe it's not meaningful to add me. Real change is property of said person.

**Comment by doraskayo** [comment]
> Based on brief glance same bug may be present in 2.3.5. 2.0.1 tag does not exist in CPython git repository so didn't check yet.

Wait, what about these other versions? Do we need a separate issue for those?

**Comment by nanonyme** [comment]
I dunno, I have never seen this problem on anything else than 2.5.6.
