### ISSUE TITLE
Early unxz support

### ISSUE THREAD

**Issue by Googulator** [fosslinux/live-bootstrap#348]
Right now, xz is built quite late, after the final Bash.
If we had an "unxz" utility early on, srcfs & download size could be significantly reduced, by preferring xz archives wherever possible.
For example, linux-4.9.10.tar.xz is 46MiB smaller than linux-4.9.10.tar.gz, which is what we currently use.

https://github.com/pts/muxzcat might be a good starting point, although this one expects input on stdin and writes output to stdout, which is incompatible with kaem.

**Comment by fosslinux** [comment]
This is probably better placed oriansj/mescc-tools-extra.

I fully agree with this in principle though.

**Comment by Googulator** [comment]
#436 achieves this.
