### ISSUE TITLE
Consider downloading all coreutils versions from Savannah (smaller file size)

### ISSUE THREAD

**Issue by Googulator** [fosslinux/live-bootstrap#350]
We currently download coreutils-5.0 and 6.10 from ftp.gnu.org, but 8.32 is downloaded from savannah.gnu.org instead. The downloads from savannah,gnu.org are considerably smaller, probably because of fewer pregenerated files included (and can be even smaller with more advanced compression options, see #349 ).

**Comment by stikonas** [comment]
Note that for coreutils 8.32 we were forced to use VCS snapshot because release tarball did not have all required files needed to regenerate files.
