### ISSUE TITLE
src_install() shouldn't touch the live system

### ISSUE THREAD

**Issue by Googulator** [fosslinux/live-bootstrap#377]
The following packages all touch the live system (adding, deleting or modifying files outside $DESTDIR) in their src_install:

- bash-2.05b (deletes old bash to avoid issues with tar later)
- bash-5.2.15 (ditto)
- coreutils-5.0 (directly creates /bin/pwd, bypassing $DESTDIR)
- flex-2.5.11 (removes lex from the live system)
- flex-2.6.4 (removes yacc from the live system)
- musl-1.1.24 (pass 3 only - removes ALL include files installed up to that point from /usr/include! This is fixed by #375 as it caused a checksum inconsistency.)
- perl5.004-05 (removes previous perl)
- perl5.005-03 (ditto)
- perl-5.6.2 (ditto)
- perl-5.10.1 (ditto)
- perl-5.32.1 (ditto)

All of these alterations to the live system will fail to be reproduced when these packages are installed from preseeded tarballs, rather than built in place.

If any of these changes is genuinely necessary, then we need to implement src_apply override support in helpers.sh, and move the relevant code there, so the proper FS changes will be made regardless of whether we're building or installing from preseed.

**Comment by stikonas** [comment]
Well, we need some way to remove old files. Normally distros have install manifests to keep track of files to be removed when installing upgrades.

**Comment by fosslinux** [comment]
To me, what makes the most sense here is adding some kind of uninstall function;
that reads a filelist (probably generated from a tarball in the repo), and removes said files.

I'd prefer actually having removal of old files in `steps/manifest` now, because removal of old files isn't really tied to any specific package.
Could have two forms, one used for generated packages and one for pre-kaem, eg

```
uninstall: perl-5.6.2 # removes the old package perl 5.6.2
uninstall: /usr/bin/lex # removes the lex binary
```

**Comment by Googulator** [comment]
Maybe that can be implemented also as improve steps (e.g. "improve: cleanup-old-perl").
