### ISSUE TITLE
working qemu checkout? kexec-fiwix: jumping to trampoline...

### ISSUE THREAD

**Issue by pyy** [fosslinux/live-bootstrap#448]
Hello everyone,
Firstly, thanks a lot for this great project! 
I tried to use --qemu to run this program, but got this, and it forever stops here.
have tried different checkout, but it is still same or similar.

Could someone give me a working checkout hint for --qemu?

`./rootfs.py --qemu --cores 10 --qemu-ram 8192 --force-timestamps --external-sources`
`./rootfs.py --qemu` results same
```
copy_file: /kaem.x86
copy_file: /aarch64.answers
copy_file: /riscv32.answers
copy_file: /amd64.answers
copy_file: /CHANGELOG.org
copy_file: /preseeded.kaem
copy_file: /makefile
copy_file: /kaem.aarch64
copy_file: /kaem.riscv64
copy_file: /x86.answers
copy_file: /README.md
copy_file: /cleanup.sh
copy_file: /after.kaem
copy_file: /e820
Fiwix ext2 initrd created successfully.
 +> if match xFalse xTrue
kexec-fiwix: starting kernel /boot/fiwix...

kexec-fiwix: Fiwix kernel file length: 375816
kexec-fiwix: Reading kernel...
ELF virtual entry point       : 0x80100030
ELF program header offset     : 0x34
ELF number of program  headers: 2
ELF size of program  headers  : 32
kexec-fiwix: Placing kernel in memory...
ELF physical entry point      : 0x100030
header 0:
    p_offset: 0x00001000
    p_paddr : 0x00100000
    p_filesz: 0x0004b5c0
    p_memsz : 0x0004b5c0
header 1:
    p_offset: 0x0004c5c0
    p_paddr : 0x0014c5c0
    p_filesz: 0x0000f4c4
    p_memsz : 0x00037df0
Preparing multiboot info for kernel...
Found image at filenum 8835
initrd_src: 0x67c7dc66
initrd_len: 0x54000000
kexec-fiwix: Memory map file length: 192
kexec-fiwix: Reading memory map file...
Preparing trampoline...
kexec-fiwix: jumping to trampoline..
```

for checkout version [493ddfa8293fc158342dc796ab6021dae2a491aa](https://github.com/fosslinux/live-bootstrap/tree/493ddfa8293fc158342dc796ab6021dae2a491aa)
it got `Kernel panic - not syncing: Attempted to kill init!`

**Comment by Googulator** [comment]
That version is extremely old; try a more recent one.

Also, is this on a 13th or 14th generation Intel CPU on the host?

**Comment by pder** [comment]
I actually included distfiles/fiwix-1.5.0-lb1.tar.gz in my newer-fiwix branch for convenience.  This tarball was created with Fiwix commit f997f3144612743d341f7dd62f01c7d07a387a88 which is what you mentioned above.  If you created your own tarball of the source you can compare it to the one I included in the commit.

I created it using this command:
cd Fiwix
tar czvf ../fiwix-1.5.0-lb1.tar.gz --transform 's,\.,fiwix-1.5.0-lb1,' --exclude-vcs .

**Comment by pder** [comment]
Could you run git status and git submodule status?

Should look like this:
`$ git status
On branch newer-fiwix
nothing to commit, working tree clean`

`$ git submodule status
 a2781242d19e6be891b453d8fa827137ab5db31a builder-hex0 (heads/main-18-ga278124)
 63fd7767db0651b703b8942cfc0c92989a3e4b25 seed/stage0-posix (Release_1.6.0-3-g63fd776)`

**Comment by ajherchenroder** [comment]
What is your host distro? I have had this same problem running on arch. My current workaround is to use nested virtualization. I run a Debian VM and then run the bootstrap in Debian. That seems to work for me.

**Comment by ajherchenroder** [comment]
I looked at my Debian VM and it’s actually Debian 11 without back ports. I don’t know if that will make a difference but it may be worth a try.
