### ISSUE TITLE
binutils-2.14: regenerate intl/aclocal.m4

### ISSUE THREAD

**Issue by fosslinux** [fosslinux/live-bootstrap#65]
This requires gettext. A probably easier option is to just disable intl entirely (its only translations and stuff).

**Comment by stikonas** [comment]
It's not just about gettext. Part of `intl/aclocal.m4` includes `gettext.m4` file but it looks to be modified and probably from the very old version of gettext that is not available on ftp.gnu.org.

**Comment by stikonas** [comment]
If we can't find any other option, I think it might also be acceptable to ship `gettext.m4` portion of `aclocal.m4` file in our `files` directory, regenerate first half of `aclocal.m4` with `aclocal` and then concatenate those.
