### ISSUE TITLE
Pregenerated texinfo files

### ISSUE THREAD

**Issue by stikonas** [fosslinux/live-bootstrap#86]
It's lower priority since  they are clearly not used for anything but eventually it would be nicer to deal with pre-built texinfo files.

We can remove them completely before texinfo is available.

That might be easier once we have staged install.

**Comment by fosslinux** [comment]
Affected packages:

- findutils-4.2.33
- coreutils-6.10

**Comment by stikonas** [comment]
There are more files installed info `/after/info` rather than `/after/share/info`. Need to remove those too.
