### ISSUE TITLE
Gnulib portability library

### ISSUE THREAD

**Issue by stikonas** [fosslinux/live-bootstrap#88]
The process of gnulib import creates some files that are not hand-written.

Those files have a comment how to reproduce them with gnulib-tool but I guess we need exact same gnulib checkout (note that there are no standalone gnulib releases).

**Comment by fosslinux** [comment]
Affected packages:

- findutils-4.2.33
- coreutils-6.10

**Comment by stikonas** [comment]
It might be a bit easier if we switch to newer versions from 2015 and later. I think they often come with ./bootstrap script to import gnulib. We still need to ship that gnulib snapshot though (or maybe even investigate if it's possible to build git and keep the whole gnulib repo).
