### ISSUE TITLE
autoconf-2.57: infrequently 6% ABORT: autom4te.cfg: No such file or directory

### ISSUE THREAD

**Issue by bittorf** [fosslinux/live-bootstrap#92]
seen with dcec416d0fe1d8d6effdfa985c9bd51995490381 and qemu-386 with kernel 3.18.140 and 3G RAM
see: http://intercity-vpn.de/bootstrap/bootstrap.log-multilog-9.txt
see: normal/OK run: http://intercity-vpn.de/bootstrap/bootstrap.log-multilog-22-1617824223.txt

happens in about 6% (12 out of 193 runs)

```
[...]
01h50m15s | autoconf-2.57: compiling source.
01h50m15s | Making all in bin
01h50m15s | make[1]: Entering directory `/after/autoconf-2.57/build/autoconf-2.57/bin'
01h50m15s | rm -f autom4te autom4te.tmp
01h50m15s | sed -e 's,@SHELL\@,/bin/sh,g' -e 's,@PERL\@,/after/bin/perl,g' -e 's,@bindir\@,/after/bin,g' -e 's,@datadir\@,/after/share/autoconf-2.57,g' -e 's,@prefix\@,/after,g' -e 's,@autoconf-name\@,'`echo autoconf | sed 's,$,-2.57,'`',g' -e 's,@autoheader-name\@,'`echo autoheader | sed 's,$,-2.57,'`',g' -e 's,@autom4te-name\@,'`echo autom4te | sed 's,$,-2.57,'`',g' -e 's,@M4\@,/after/bin/m4,g' -e 's,@AWK\@,gawk,g' -e 's,@VERSION\@,2.57,g' -e 's,@PACKAGE_NAME\@,GNU Autoconf,g' ./autom4te.in >autom4te.tmp
01h50m15s | chmod +x autom4te.tmp
01h50m15s | mv autom4te.tmp autom4te
01h50m15s | ../tests/autom4te --language M4sh --cache '' ./autoconf.as -o autoconf.in
01h50m15s | autom4te: cannot open /after/autoconf-2.57/build/autoconf-2.57/lib/autom4te.cfg: No such file or directory
01h50m15s | at /after/autoconf-2.57/build/autoconf-2.57/bin/autom4te line 455
01h50m15s | make[1]: *** [autoconf.in] Error 1
01h50m15s | make[1]: Leaving directory `/after/autoconf-2.57/build/autoconf-2.57/bin'
01h50m15s | make: *** [all-recursive] Error 1
01h50m15s | Subprocess error 512
01h50m15s | ABORTING HARD
```

**Comment by bittorf** [comment]
after adding high resolution timers to kernel, it still happens:
```
CONFIG_HIGH_RES_TIMERS=y
CONFIG_SCHED_HRTICK=y
CONFIG_HZ_100=y
```

good: http://intercity-vpn.de/bootstrap/bootstrap.log-multilog-1-1617877552.txt 
bad: http://intercity-vpn.de/bootstrap/bootstrap.log-multilog-14-1617877552.txt

**Comment by bauen1** [comment]
Some summary of my findings I've posted to IRC:

At least for `autoconf-2.57` `bin/Makefile.in` (source of `bin/Makefile`) contains a target for `bin/autoconf.in` from `bin/autoconf.as`.
This target is missing correct dependencies, as indicated by a FIXME in said Makefile.
This also hints at `bin/autoconf.in` being a pre generated file that we should probably remove.
